name: CI/CD Best Practices

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: "my-app-image"

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    permissions:
        contents: read
        id-token: write

    steps:
      - name: status check
        run: echo "The workflow is running"

      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Lint code
        run: npm run lint

      