name: test self-hosted runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: display vars
        run: |
          echo "environment var: ${{ vars.THIS_ENV }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "GITHUB_RUN_ID: ${{ github.run_id }}"
          echo "GITHUB_RUN_NUMBER: ${{ github.run_number }}"
          echo "GITHUB_JOB: ${{ github.job }}"
          