name: test self-hosted runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: read var this_env from environment variable
        env:
          MY_ENV_VAR: ${{ vars.MY_ENV_VAR }}
        run: echo "The value of MY_ENV_VAR is $MY_ENV_VAR"